package views

const (
	templatesFolder     string = "templates"
	TemplateCSS         string = "../static/styles/template.css"
	LoginCSS            string = "../static/styles/style.css"
	RegisterCSS         string = "../static/styles/register-style.css"
	TemplateJS          string = "../static/scripts/template-script.js"
	LoginJS             string = "../static/scripts/app-login.js"
	RegisterJS          string = "../static/scripts/app-register.js"
	AboutJS             string = "../static/scripts/app-about.js"
	DonateJS            string = "../static/scripts/app-donate.js"
	RegisterTitle       string = "Register"
	IndexTitle          string = "Index"
	LoginTitle          string = "Login"
	AboutTitle          string = "About"
	DonateTitle         string = "Donate"
	BaseTemplate        string = "base.html"
	RegisterTemplate    string = "register.html"
	LoginTemplate       string = "login.html"
	IndexTemplate       string = "index.html"
	AboutTemplate       string = "about.html"
	DonateTemplate      string = "donate.html"
	TemplateRenderError string = "Error rendering page template"
	NoFilePathsError    string = "no filepaths provided"
)
